import type { SkinRouteBuildDefinition } from '../src/skins/runtime/build-contracts'
import { assertSkinRouteAllowed } from '../src/skins/runtime/route-policy'

const GENERATED_HEADER = '/* generated by scripts/generate-skin.ts */'

export function normalizeSkinId(value: string | undefined): string {
  const skinId = value?.trim() || 'default'
  if (!/^[a-z0-9-]+$/.test(skinId)) {
    throw new Error(`Invalid APP_SKIN value: ${skinId}`)
  }
  return skinId
}

export function renderActiveSkinModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkin } from '@/skins/${skinId}/manifest'\n`
}

export function renderActiveBuildModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkinBuild } from '@/skins/${skinId}/build-manifest'\n`
}

export function validateSkinRoutes(
  routes: readonly SkinRouteBuildDefinition[]
): SkinRouteBuildDefinition[] {
  const routeIds = new Set<string>()
  const routePaths = new Set<string>()

  for (const route of routes) {
    if (route.id.trim() === '') {
      throw new Error('Skin route has an empty skin route ID')
    }
    if (route.componentImport.trim() === '') {
      throw new Error(`Skin route "${route.id}" has an empty component import`)
    }

    assertSkinRouteAllowed(route.path)

    if (routeIds.has(route.id)) {
      throw new Error(`Duplicate skin route ID: ${route.id}`)
    }
    if (routePaths.has(route.path)) {
      throw new Error(`Duplicate skin route path: ${route.path}`)
    }

    routeIds.add(route.id)
    routePaths.add(route.path)
  }

  return [...routes].sort((left, right) => left.path.localeCompare(right.path))
}

export function getGeneratedRouteFile(routePath: string): string {
  assertSkinRouteAllowed(routePath)
  const segments = routePath.slice(1).split('/')

  return `(skin-generated)/${segments.join('/')}.tsx`
}

export function renderGeneratedRoute(route: SkinRouteBuildDefinition): string {
  const generatedRoutePath = getGeneratedRouteFile(route.path).replace(/\.tsx$/, '')

  return `${GENERATED_HEADER}
import { createFileRoute } from '@tanstack/react-router'
import { ActiveSkinRoute } from '@/skins/runtime/active-skin-route'

export const Route = createFileRoute('/${generatedRoutePath}')({
  component: () => <ActiveSkinRoute routeId='${route.id}' />,
})
`
}
