import type { SkinRouteBuildDefinition } from '../src/skins/runtime/build-contracts'
import { assertSkinRouteAllowed } from '../src/skins/runtime/route-policy'

const GENERATED_HEADER = '/* generated by scripts/generate-skin.ts */'
const GENERATED_ROUTE_PREFIX = '(skin-generated)/'
const DYNAMIC_ROUTE_SEGMENT = /^\$[A-Za-z][A-Za-z0-9_]*$/
const STATIC_ROUTE_SEGMENT = /^[A-Za-z0-9-]+$/

export function normalizeSkinId(value: string | undefined): string {
  const skinId = value?.trim() || 'default'
  if (!/^[a-z0-9-]+$/.test(skinId)) {
    throw new Error(`Invalid APP_SKIN value: ${skinId}`)
  }
  return skinId
}

export function renderActiveSkinModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkin } from '@/skins/${skinId}/manifest'\n`
}

export function renderActiveBuildModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkinBuild } from '@/skins/${skinId}/build-manifest'\n`
}

export function validateSkinRoutes(
  routes: readonly SkinRouteBuildDefinition[]
): SkinRouteBuildDefinition[] {
  const routeIds = new Set<string>()
  const routePaths = new Set<string>()
  const generatedRouteFiles = new Set<string>()

  for (const route of routes) {
    if (route.id.trim() === '') {
      throw new Error('Skin route has an empty skin route ID')
    }
    if (route.componentImport.trim() === '') {
      throw new Error(`Skin route "${route.id}" has an empty component import`)
    }

    assertSkinRouteAllowed(route.path)

    if (route.navigation) {
      if (
        typeof route.navigation.labelKey !== 'string' ||
        route.navigation.labelKey.trim() === ''
      ) {
        throw new Error(`Skin route navigation label is empty: ${route.path}`)
      }
      if (
        route.navigation.position !== 'header' &&
        route.navigation.position !== 'footer'
      ) {
        throw new Error(
          `Invalid skin route navigation position for ${route.path}: ${String(route.navigation.position)}`
        )
      }
      if (
        route.navigation.order !== undefined &&
        (!Number.isInteger(route.navigation.order) || route.navigation.order < 0)
      ) {
        throw new Error(
          `Invalid skin route navigation order for ${route.path}: ${String(route.navigation.order)}`
        )
      }
    }

    if (routeIds.has(route.id)) {
      throw new Error(`Duplicate skin route ID: ${route.id}`)
    }
    if (routePaths.has(route.path)) {
      throw new Error(`Duplicate skin route path: ${route.path}`)
    }

    const generatedRouteFile = getGeneratedRouteFile(route.path).toLocaleLowerCase('en-US')
    if (generatedRouteFiles.has(generatedRouteFile)) {
      throw new Error(`Generated route file collision: ${generatedRouteFile}`)
    }

    routeIds.add(route.id)
    routePaths.add(route.path)
    generatedRouteFiles.add(generatedRouteFile)
  }

  return [...routes].sort((left, right) => left.path.localeCompare(right.path))
}

export function getGeneratedRouteFile(routePath: string): string {
  assertSkinRouteAllowed(routePath)
  const segments = routePath.slice(1).split('/')
  for (const segment of segments) {
    const isDynamicSegment = segment.startsWith('$')
    const isValidDynamicSegment = isDynamicSegment && DYNAMIC_ROUTE_SEGMENT.test(segment)
    const isReservedStaticSegment = segment === 'index' || segment === 'route'
    const isValidStaticSegment =
      !isDynamicSegment && !isReservedStaticSegment && STATIC_ROUTE_SEGMENT.test(segment)

    if (!isValidDynamicSegment && !isValidStaticSegment) {
      throw new Error(`Invalid skin route file segment: ${segment}`)
    }
  }

  return `${GENERATED_ROUTE_PREFIX}${segments.join('/')}.tsx`
}

export function renderGeneratedRoute(route: SkinRouteBuildDefinition): string {
  const generatedRoutePath = getGeneratedRouteFile(route.path).replace(/\.tsx$/, '')

  return `${GENERATED_HEADER}
import { createFileRoute } from '@tanstack/react-router'
import { ActiveSkinRoute } from '@/skins/runtime/skin-route'

export const Route = createFileRoute('/${generatedRoutePath}')({
  component: () => <ActiveSkinRoute routeId={${JSON.stringify(route.id)}} routePath={${JSON.stringify(route.path)}} />,
})
`
}
