const GENERATED_HEADER = '/* generated by scripts/generate-skin.ts */'

export function normalizeSkinId(value: string | undefined): string {
  const skinId = value?.trim() || 'default'
  if (!/^[a-z0-9-]+$/.test(skinId)) {
    throw new Error(`Invalid APP_SKIN value: ${skinId}`)
  }
  return skinId
}

export function renderActiveSkinModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkin } from '@/skins/${skinId}/manifest'\n`
}

export function renderActiveBuildModule(skinId: string): string {
  return `${GENERATED_HEADER}\nexport { default as activeSkinBuild } from '@/skins/${skinId}/build-manifest'\n`
}
