package webseo

import (
	"fmt"
	"html"
	"net/url"
	"sort"
	"strings"

	"github.com/QuantumNous/new-api/model"
)

const (
	siteLogoURL      = "https://s3.lizh.ai/reference-uploads/misc/1780350609481-avbe08b-auth-logo.png"
	supportEmail     = "service@lizh.ai"
	priceClarifierZH = "实际价格以账户分组和结算配置为准"
	priceClarifierEN = "Actual prices depend on account groups and settlement configuration."
)

func BuildBodyContent(meta Meta, requestURI string, baseURL string, pricings []model.Pricing, theme string) string {
	if meta.Robots != indexRobots {
		return ""
	}
	path := normalizePath(requestURI)
	base := normalizeBaseURL(baseURL)
	catalog := BuildCatalog(pricings)

	switch {
	case path == "/":
		return renderHomeBody(base, catalog, theme)
	case path == "/pricing":
		return renderPricingBody(base, catalog)
	case strings.HasPrefix(path, "/pricing/"):
		modelID, err := url.PathUnescape(strings.TrimPrefix(path, "/pricing/"))
		if err != nil {
			modelID = strings.TrimPrefix(path, "/pricing/")
		}
		if item, ok := findModel(catalog, modelID); ok {
			return renderModelBody(base, catalog, item)
		}
	case path == "/rankings" && theme != "classic":
		return renderRankingsBody(base, catalog)
	case path == "/about":
		return renderAboutBody(base)
	case topicPage(path) != nil:
		return renderTopicBody(base, catalog, *topicPage(path))
	}
	return ""
}

func renderHomeBody(base string, catalog []ModelSEOItem, theme string) string {
	var b strings.Builder
	startArticle(&b, "Lizh AI AI Model Marketplace")
	writeParagraph(&b, "Lizh AI is an AI model marketplace for developers who need OpenAI-compatible access to GPT, Gemini, DeepSeek, Qwen, Doubao, GLM, MiniMax, Kimi, and other mainstream models through one API gateway.")
	writeSection(&b, "Supported AI models", "Browse a compact catalog of text, image, multimodal, and tool-capable AI models. Every model page links to pricing, model IDs, capabilities, and integration notes.")
	writeModelLinks(&b, catalog, len(catalog))
	writeSection(&b, "Unified API and billing", "Use one account balance, one integration surface, and one model marketplace to compare costs and route workloads across providers. "+priceClarifierEN)
	writeSection(&b, "Developer entry points", "Start from model pricing, compare API costs, or read an OpenAI SDK compatibility guide before creating production keys.")
	links := []linkItem{
		{Text: "Model pricing marketplace", Href: "/pricing"},
		{Text: "About Lizh AI", Href: "/about"},
		{Text: "OpenAI-compatible API guide", Href: "/use-cases/openai-compatible-api"},
		{Text: "AI API pricing comparison", Href: "/compare/ai-api-pricing"},
	}
	if theme != "classic" {
		links = append(links, linkItem{Text: "Popular AI model rankings", Href: "/rankings"})
	}
	writeLinkList(&b, "Explore Lizh AI", links)
	endArticle(&b)
	return b.String()
}

func renderPricingBody(base string, catalog []ModelSEOItem) string {
	var b strings.Builder
	startArticle(&b, "AI Model API Pricing Marketplace")
	writeParagraph(&b, "Compare all available model prices in Lizh AI. The marketplace lists model IDs, families, input and output prices, and capability summaries for developers building with AI APIs.")
	writeSection(&b, "How API pricing works", "Token-based models usually separate input and output prices. Some models may also have cache, image, audio, video, or request-based pricing. "+priceClarifierEN)
	writeHeading(&b, "All available model prices")
	writeModelTable(&b, catalog)
	writeFAQ(&b, []faqItem{
		{Question: "How is AI API pricing calculated?", Answer: "Pricing is based on the model configuration, usage type, and account settlement rules. Token models usually have separate input and output prices."},
		{Question: "What is the difference between input and output price?", Answer: "Input price applies to prompt tokens sent to the model. Output price applies to tokens generated by the model."},
		{Question: "Is Lizh AI compatible with the OpenAI SDK?", Answer: "Lizh AI is designed around OpenAI-compatible API access for mainstream model families."},
		{Question: "How should I choose a low-cost model?", Answer: "Compare input/output prices, capabilities, latency needs, and whether the workload needs multimodal or tool features."},
	})
	endArticle(&b)
	_ = base
	return b.String()
}

func renderModelBody(base string, catalog []ModelSEOItem, item ModelSEOItem) string {
	var b strings.Builder
	startArticle(&b, item.Name+" API Pricing")
	writeParagraph(&b, modelIntro(item))
	writeHeading(&b, "Price summary")
	b.WriteString(`<table><tbody>`)
	writeTableRow(&b, "Model ID", item.ID)
	writeTableRow(&b, "Family", item.Family)
	writeTableRow(&b, "Input price", "约 "+formatPrice(item.InputPrice))
	writeTableRow(&b, "Output price", "约 "+formatPrice(item.OutputPrice))
	writeTableRow(&b, "Capabilities", strings.Join(item.Capabilities, ", "))
	b.WriteString(`</tbody></table>`)
	writeParagraph(&b, priceClarifierEN+" "+priceClarifierZH+"。")
	writeSection(&b, "OpenAI-compatible access", fmt.Sprintf("Use model ID %s through Lizh AI's OpenAI-compatible API gateway when this model is enabled for your account.", item.ID))
	writeSection(&b, "Recommended use cases", strings.Join(modelScenarios(item), " "))
	writeLinkList(&b, "Related model links", relatedLinks(catalog, item))
	writeFAQ(&b, []faqItem{
		{Question: fmt.Sprintf("How do I access the %s API?", item.Name), Answer: fmt.Sprintf("Use the model ID %s from an API key in Lizh AI. The gateway is designed for OpenAI-compatible client usage.", item.ID)},
		{Question: fmt.Sprintf("What are the %s input and output prices?", item.Name), Answer: fmt.Sprintf("The approximate input price is %s and the approximate output price is %s. %s", formatPrice(item.InputPrice), formatPrice(item.OutputPrice), priceClarifierEN)},
		{Question: fmt.Sprintf("What is %s best suited for?", item.Name), Answer: strings.Join(modelScenarios(item), " ")},
		{Question: fmt.Sprintf("Is %s compatible with the OpenAI SDK?", item.Name), Answer: "Lizh AI exposes OpenAI-compatible access patterns for supported models."},
		{Question: fmt.Sprintf("Does %s support image, tool, or structured-output workflows?", item.Name), Answer: "Supported workflows depend on the model capabilities shown on this page and in the live model marketplace."},
	})
	endArticle(&b)
	_ = base
	return b.String()
}

func renderRankingsBody(base string, catalog []ModelSEOItem) string {
	var b strings.Builder
	startArticle(&b, "Popular AI Model Rankings")
	writeParagraph(&b, "The rankings page helps developers discover widely used GPT, Gemini, DeepSeek, Qwen, Doubao, GLM, MiniMax, Kimi, and other model families available through Lizh AI.")
	writeSection(&b, "Ranking intent", "Use rankings as a discovery entry point, then open model pricing pages to compare costs, capabilities, and model IDs.")
	writeHeading(&b, "Model directory fallback")
	writeModelLinks(&b, catalog, len(catalog))
	writeLinkList(&b, "Continue exploring", []linkItem{{Text: "AI model pricing", Href: "/pricing"}, {Text: "AI API pricing comparison", Href: "/compare/ai-api-pricing"}})
	endArticle(&b)
	_ = base
	return b.String()
}

func renderAboutBody(base string) string {
	var b strings.Builder
	startArticle(&b, "About Lizh AI")
	b.WriteString(`<p><img src="`)
	b.WriteString(html.EscapeString(siteLogoURL))
	b.WriteString(`" alt="Lizh AI logo"></p>`)
	writeParagraph(&b, "Lizh AI is an AI model marketplace for overseas developers and teams that need multi-model API access, transparent pricing, and OpenAI-compatible integration paths.")
	writeSection(&b, "Product positioning", "Lizh AI focuses on model discovery, API pricing comparison, unified account settlement, and developer-friendly model access.")
	writeSection(&b, "Who it is for", "The platform is built for application developers, AI product teams, automation builders, and teams comparing mainstream AI model costs.")
	writeSection(&b, "Support", "For support, contact "+supportEmail+". Telegram support and community links may be added later.")
	writeLinkList(&b, "Key pages", []linkItem{{Text: "Model pricing marketplace", Href: "/pricing"}, {Text: "OpenAI-compatible API", Href: "/use-cases/openai-compatible-api"}, {Text: "OpenAI SDK guide", Href: "/guides/openai-sdk-compatible"}})
	endArticle(&b)
	_ = base
	return b.String()
}

type topicDefinition struct {
	Path        string
	H1          string
	Title       string
	Description string
	Intro       string
	Sections    []contentSection
	FAQ         []faqItem
	PrimaryLink string
}

type contentSection struct {
	Title string
	Body  string
}

func renderTopicBody(base string, catalog []ModelSEOItem, topic topicDefinition) string {
	var b strings.Builder
	startArticle(&b, topic.H1)
	writeParagraph(&b, topic.Intro)
	for _, section := range topic.Sections {
		writeSection(&b, section.Title, section.Body)
	}
	writeHeading(&b, "Related model pages")
	writeModelLinks(&b, filterTopicModels(catalog, topic.Path), len(catalog))
	links := []linkItem{{Text: "AI model pricing", Href: "/pricing"}}
	if topic.PrimaryLink != "" {
		links = append(links, linkItem{Text: "Related guide", Href: topic.PrimaryLink})
	}
	writeLinkList(&b, "Continue reading", links)
	writeFAQ(&b, topic.FAQ)
	endArticle(&b)
	_ = base
	return b.String()
}

func topicPage(path string) *topicDefinition {
	for _, topic := range topicPages() {
		if topic.Path == path {
			topicCopy := topic
			return &topicCopy
		}
	}
	return nil
}

func topicPages() []topicDefinition {
	return []topicDefinition{
		{
			Path:        "/use-cases/openai-compatible-api",
			H1:          "OpenAI-Compatible API for Multiple AI Models",
			Title:       "OpenAI-Compatible API for GPT, Gemini, DeepSeek and Qwen | Lizh AI",
			Description: "Use Lizh AI as an OpenAI-compatible API gateway for GPT, Gemini, DeepSeek, Qwen, Doubao, GLM, MiniMax, Kimi, and other mainstream AI models.",
			Intro:       "Lizh AI provides an OpenAI-compatible gateway for developers who want to test and route multiple mainstream AI models without rebuilding every client integration.",
			Sections: []contentSection{
				{Title: "Why developers use Lizh AI", Body: "A single API marketplace makes it easier to compare GPT, Gemini, DeepSeek, Qwen, and other model families while keeping integration work predictable."},
				{Title: "Unified model switching", Body: "Use model IDs from the pricing marketplace to switch workloads between providers and price tiers."},
			},
			FAQ:         standardTopicFAQ("OpenAI-compatible API"),
			PrimaryLink: "/guides/openai-sdk-compatible",
		},
		{
			Path:        "/compare/ai-api-pricing",
			H1:          "AI API Pricing Comparison",
			Title:       "AI API Pricing Comparison for Mainstream Models | Lizh AI",
			Description: "Compare approximate AI API prices across GPT, Gemini, DeepSeek, Qwen, Doubao, GLM, MiniMax, Kimi, and other models available in Lizh AI.",
			Intro:       "Compare AI API prices across mainstream models and understand input, output, multimodal, and request-based billing patterns.",
			Sections: []contentSection{
				{Title: "Compare by workload", Body: "Different workloads care about different prices: chat prompts, generated tokens, image generation, and structured tool workflows can each have different cost drivers."},
				{Title: "Use price plus capability", Body: "The cheapest model is not always the best fit. Compare price together with model family, capability, and SDK compatibility."},
			},
			FAQ:         standardTopicFAQ("AI API pricing"),
			PrimaryLink: "/pricing",
		},
		{
			Path:        "/providers/gemini-api",
			H1:          "Gemini API Pricing and Access",
			Title:       "Gemini API Pricing and Model Access | Lizh AI",
			Description: "Explore Gemini API model options, approximate prices, model IDs, and OpenAI-compatible access paths through Lizh AI.",
			Intro:       "Explore Gemini API model options, approximate prices, and OpenAI-compatible access paths through Lizh AI.",
			Sections:    providerSections("Gemini"),
			FAQ:         standardTopicFAQ("Gemini API"),
			PrimaryLink: "/pricing",
		},
		{
			Path:        "/providers/deepseek-api",
			H1:          "DeepSeek API Pricing and Access",
			Title:       "DeepSeek API Pricing and Model Access | Lizh AI",
			Description: "Explore DeepSeek API options for reasoning, coding, and cost-conscious AI workloads with approximate prices and model IDs in Lizh AI.",
			Intro:       "Explore DeepSeek API options for reasoning, coding, and cost-conscious AI workloads through Lizh AI.",
			Sections:    providerSections("DeepSeek"),
			FAQ:         standardTopicFAQ("DeepSeek API"),
			PrimaryLink: "/pricing",
		},
		{
			Path:        "/providers/qwen-api",
			H1:          "Qwen API Pricing and Access",
			Title:       "Qwen API Pricing and Model Access | Lizh AI",
			Description: "Explore Qwen API pricing, model IDs, multilingual and coding use cases, and OpenAI-compatible access through Lizh AI.",
			Intro:       "Explore Qwen API pricing, model IDs, and integration options in the Lizh AI model marketplace.",
			Sections:    providerSections("Qwen"),
			FAQ:         standardTopicFAQ("Qwen API"),
			PrimaryLink: "/pricing",
		},
		{
			Path:        "/guides/openai-sdk-compatible",
			H1:          "OpenAI SDK Compatible AI Model Access",
			Title:       "OpenAI SDK Compatible API Guide for Multiple AI Models | Lizh AI",
			Description: "Learn how to use OpenAI-compatible client patterns, API base URLs, API keys, and model IDs to access multiple AI model families from Lizh AI.",
			Intro:       "Use OpenAI-compatible client patterns to access multiple AI model families from Lizh AI with minimal integration changes.",
			Sections: []contentSection{
				{Title: "Integration approach", Body: "Configure your API base URL, API key, and model ID, then call supported chat or response endpoints according to the model capability."},
				{Title: "Model selection", Body: "Start from the pricing marketplace, pick a model ID, and verify whether the model supports your text, image, or structured-output workflow."},
			},
			FAQ:         standardTopicFAQ("OpenAI SDK compatibility"),
			PrimaryLink: "/use-cases/openai-compatible-api",
		},
	}
}

func providerSections(provider string) []contentSection {
	return []contentSection{
		{Title: provider + " model marketplace", Body: "Use Lizh AI to compare available " + provider + " models, prices, and model IDs from one AI model marketplace."},
		{Title: "API access", Body: provider + " model access can be evaluated alongside GPT, DeepSeek, Qwen, and other mainstream model families."},
	}
}

func standardTopicFAQ(topic string) []faqItem {
	return []faqItem{
		{Question: "What is " + topic + " in Lizh AI?", Answer: "It is a public topic page that explains model access, pricing, and integration paths in the Lizh AI marketplace."},
		{Question: "Where can I compare prices?", Answer: "Use the pricing marketplace to compare all available model prices and detail pages."},
		{Question: "Are prices final billing guarantees?", Answer: priceClarifierEN},
	}
}

func filterTopicModels(catalog []ModelSEOItem, path string) []ModelSEOItem {
	if strings.Contains(path, "gemini") {
		return filterFamily(catalog, "gemini")
	}
	if strings.Contains(path, "deepseek") {
		return filterFamily(catalog, "deepseek")
	}
	if strings.Contains(path, "qwen") {
		return filterFamily(catalog, "qwen")
	}
	return catalog
}

func filterFamily(catalog []ModelSEOItem, family string) []ModelSEOItem {
	filtered := make([]ModelSEOItem, 0)
	for _, item := range catalog {
		if strings.Contains(strings.ToLower(item.ID), family) || strings.Contains(strings.ToLower(item.Family), family) {
			filtered = append(filtered, item)
		}
	}
	if len(filtered) == 0 {
		return catalog
	}
	return filtered
}

func modelIntro(item ModelSEOItem) string {
	description := strings.TrimSpace(item.Description)
	if description != "" {
		return fmt.Sprintf("%s API is available in Lizh AI. %s", item.Name, description)
	}
	return fmt.Sprintf("%s API is part of the %s model family in the Lizh AI AI model marketplace.", item.Name, item.Family)
}

func modelScenarios(item ModelSEOItem) []string {
	scenarios := []string{"Use it for API workloads that need " + strings.Join(item.Capabilities, ", ") + "."}
	lower := strings.ToLower(item.ID + " " + item.Family)
	switch {
	case strings.Contains(lower, "deepseek"):
		scenarios = append(scenarios, "It is a good candidate for reasoning, coding, and cost-sensitive development workflows.")
	case strings.Contains(lower, "gemini"):
		scenarios = append(scenarios, "It is useful for multimodal and general-purpose application workflows.")
	case strings.Contains(lower, "qwen"):
		scenarios = append(scenarios, "It is useful for multilingual, coding, and general assistant workloads.")
	case strings.Contains(lower, "gpt"):
		scenarios = append(scenarios, "It is useful for general reasoning, coding, and production assistant experiences.")
	}
	return scenarios
}

type linkItem struct {
	Text string
	Href string
}

type faqItem struct {
	Question string
	Answer   string
}

func startArticle(builder *strings.Builder, h1 string) {
	builder.WriteString(`<article class="seo-content">`)
	builder.WriteString(`<h1>`)
	builder.WriteString(html.EscapeString(h1))
	builder.WriteString(`</h1>`)
}

func endArticle(builder *strings.Builder) {
	builder.WriteString(`</article>`)
}

func writeHeading(builder *strings.Builder, heading string) {
	builder.WriteString(`<h2>`)
	builder.WriteString(html.EscapeString(heading))
	builder.WriteString(`</h2>`)
}

func writeParagraph(builder *strings.Builder, text string) {
	builder.WriteString(`<p>`)
	builder.WriteString(html.EscapeString(text))
	builder.WriteString(`</p>`)
}

func writeSection(builder *strings.Builder, heading string, text string) {
	writeHeading(builder, heading)
	writeParagraph(builder, text)
}

func writeLinkList(builder *strings.Builder, heading string, links []linkItem) {
	writeHeading(builder, heading)
	builder.WriteString(`<ul>`)
	for _, link := range links {
		builder.WriteString(`<li><a href="`)
		builder.WriteString(html.EscapeString(link.Href))
		builder.WriteString(`">`)
		builder.WriteString(html.EscapeString(link.Text))
		builder.WriteString(`</a></li>`)
	}
	builder.WriteString(`</ul>`)
}

func writeModelLinks(builder *strings.Builder, catalog []ModelSEOItem, limit int) {
	builder.WriteString(`<ul>`)
	for idx, item := range catalog {
		if limit > 0 && idx >= limit {
			break
		}
		builder.WriteString(`<li><a href="`)
		builder.WriteString(html.EscapeString(modelURLPath(item.ID)))
		builder.WriteString(`">`)
		builder.WriteString(html.EscapeString(item.Name))
		builder.WriteString(` API pricing</a> - `)
		builder.WriteString(html.EscapeString(strings.Join(item.Capabilities, ", ")))
		builder.WriteString(`</li>`)
	}
	builder.WriteString(`</ul>`)
}

func writeModelTable(builder *strings.Builder, catalog []ModelSEOItem) {
	builder.WriteString(`<table><thead><tr><th>Model</th><th>Family</th><th>Input</th><th>Output</th><th>Capabilities</th></tr></thead><tbody>`)
	for _, item := range catalog {
		builder.WriteString(`<tr><td><a href="`)
		builder.WriteString(html.EscapeString(modelURLPath(item.ID)))
		builder.WriteString(`">`)
		builder.WriteString(html.EscapeString(item.Name))
		builder.WriteString(`</a></td><td>`)
		builder.WriteString(html.EscapeString(item.Family))
		builder.WriteString(`</td><td>约 `)
		builder.WriteString(html.EscapeString(formatPrice(item.InputPrice)))
		builder.WriteString(`</td><td>约 `)
		builder.WriteString(html.EscapeString(formatPrice(item.OutputPrice)))
		builder.WriteString(`</td><td>`)
		builder.WriteString(html.EscapeString(strings.Join(item.Capabilities, ", ")))
		builder.WriteString(`</td></tr>`)
	}
	builder.WriteString(`</tbody></table>`)
}

func writeTableRow(builder *strings.Builder, header string, value string) {
	builder.WriteString(`<tr><th>`)
	builder.WriteString(html.EscapeString(header))
	builder.WriteString(`</th><td>`)
	builder.WriteString(html.EscapeString(value))
	builder.WriteString(`</td></tr>`)
}

func writeFAQ(builder *strings.Builder, items []faqItem) {
	writeHeading(builder, "FAQ")
	for _, item := range items {
		builder.WriteString(`<section><h3>`)
		builder.WriteString(html.EscapeString(item.Question))
		builder.WriteString(`</h3><p>`)
		builder.WriteString(html.EscapeString(item.Answer))
		builder.WriteString(`</p></section>`)
	}
}

func relatedLinks(catalog []ModelSEOItem, current ModelSEOItem) []linkItem {
	links := []linkItem{{Text: "All AI model prices", Href: "/pricing"}}
	sameFamily := make([]ModelSEOItem, 0)
	for _, item := range catalog {
		if item.ID == current.ID {
			continue
		}
		if item.Family == current.Family {
			sameFamily = append(sameFamily, item)
		}
	}
	sort.Slice(sameFamily, func(i, j int) bool {
		return sameFamily[i].InputPrice < sameFamily[j].InputPrice
	})
	for _, item := range sameFamily {
		if len(links) >= 5 {
			break
		}
		links = append(links, linkItem{Text: item.Name + " API pricing", Href: modelURLPath(item.ID)})
	}
	for _, item := range catalog {
		if len(links) >= 5 {
			break
		}
		if item.ID != current.ID && item.Family != current.Family {
			links = append(links, linkItem{Text: item.Name + " API pricing", Href: modelURLPath(item.ID)})
		}
	}
	return links
}
