/* generated by scripts/generate-skin.ts */
import type skinBuildManifest from '@/skins/default/build-manifest'
import skinManifest from '@/skins/default/manifest'
import type { ThemeManifestFor } from '@/skins/runtime/contracts'

const checkedManifest: ThemeManifestFor<typeof skinBuildManifest> = skinManifest
void checkedManifest

export { skinManifest as activeSkin }
